### ISSUE TITLE
PHP Auto Import

### ISSUE THREAD

**Issue by mikebronner** [alexanderflink/nova-tabnine#12]
TabNine says it implemented auto importing already, but it doesn't seem to work: https://github.com/codota/tabnine-vscode/issues/44#issuecomment-639081205

I don't see the option for experimental auto imports anywhere when typing `TabNine::config` to open my local configuration.

I'm currently evaluating TabNine with your plugin, and am liking it so far. This is the only real piece of functionality it currently seems to be missing.

Any suggestions? Thanks!

**Comment by alexanderflink** [comment]
Hi! Sorry, I was not aware this feature existed. Does Nova auto import files as you type, but TabNine overrides that behaviour?

**Comment by mikebronner** [comment]
Hi @alexanderflink 

Nova by itself doesn't do that, but my other auto-complete provider does (Intelephense). I'm not sure that TabNine **can** do it (maybe I'm misreading, or maybe its still bugged), just wanted to raise visibility. :) I'm eager to see what you find out.

**Comment by alexanderflink** [comment]
This seems to be an issue with TabNine rather than this extension. Closing for now! 🙂
