### ISSUE TITLE
Can't access TabNine config

### ISSUE THREAD

**Issue by CarterBrehm** [alexanderflink/nova-tabnine#17]
Hello, running the latest version of Nova (v9.1) and I can't seem to open the TabNine config. I'm typing `TabNine::config` in the command window and nothing happens.

**Comment by alexanderflink** [comment]
Hey @CarterBrehm! Thanks for your feedback. I'm not able to reproduce this in Nova 9.1.
Have you tried restarting the extension?

**Comment by robertoranon** [comment]
Hello, I had the same issue with 9.1, then tabnine stopped working ... tried to uninstall and reinstall the extension, with no progress

**Comment by CarterBrehm** [comment]
<img width="502" alt="CleanShot 2022-03-30 at 11 19 39@2x" src="https://user-images.githubusercontent.com/26262673/160883126-9e93bef3-5681-4505-bcee-9b4107f5b62d.png">

This is what I'm putting in the command window (`CMD+Shift+P`). After I click enter, the window disappears and nothing happens. The rest of the extension seems to function as normal, so I'm continuing to use it, but it'd be useful to access the settings.

<img width="322" alt="CleanShot 2022-03-30 at 11 20 56@2x" src="https://user-images.githubusercontent.com/26262673/160883719-1e55f362-a0d1-454d-bcab-850223b3f8d4.png">

**Comment by alexanderflink** [comment]
@CarterBrehm You need to write `TabNine::config` in any open file in your editor. It's not an available Nova command, but rather something you communicate to the TabNine binary.

I have noticed however there's a bug where sometimes the TabNine binary exits and doesn't open. In this case you need to restart the extension. Will look into this.
