### ISSUE TITLE
Unable to configure TabNine in the extension

### ISSUE THREAD

**Issue by lambertjosh** [alexanderflink/nova-tabnine#18]
I'm trying to get started with TabNine and this extension, and have a free account. When running config it pops open a browser window, but I am getting the error in the UI attached below. I am logged in in another tab, and can browse my user profile, etc.

Any help would be appreciated!

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/25085430/205964968-31699b6c-7104-4bd8-9f55-fcff98d71a23.png">

**Comment by quux-aivar** [comment]
I had similar issue. Copy link and open in another browser, for example in Chrome.

**Comment by alexanderflink** [comment]
Closing as method above seems to be working

**Comment by quux-aivar** [comment]
World be nice if it actually worked in Safari. It is pretty annoying that feature doesn’t work on macOS default browser and you have to copy the link all the time and open it in Chrome,
