### ISSUE TITLE
What is tabnine?

### ISSUE THREAD

**Issue by OKNoah** [alexanderflink/nova-tabnine#2]

**Comment by alexanderflink** [comment]
TabNine is an all-language autocompleter using machine learning! I didn't write it. I should probably add a description to the plugin.
[https://www.tabnine.com/](https://www.tabnine.com/)

**Comment by OKNoah** [comment]
> TabNine is an all-language autocompleter using machine learning! I didn't write it. I should probably add a description to the plugin.
> https://www.tabnine.com/

Thanks. I was worried I was being rude, but I did search for it and came up with nothing. Thanks.
