### ISSUE TITLE
Crashes on completion in Nova 5

### ISSUE THREAD

**Issue by alexanderflink** [alexanderflink/nova-tabnine#7]
Nova 5 seems to crash whenever a completion is made with this extension...

**Comment by jonathan-wondereur** [comment]
I also see this issue. Any timeline for a fix?

**Comment by carlosgavina** [comment]
👋  happening to me as well on Nova 5 `Build 245280`

**Comment by Incognito-sys** [comment]
Same here!

**Comment by alexanderflink** [comment]
Hello! I did some testing and unfortunately it seems to be a Nova 5 bug. I've created a bug report [here](https://devforum.nova.app/t/additionaltextedit-crash/605) and a reproducible example [here](https://github.com/alexanderflink/additionalTextEdits-bug/blob/master/Scripts/main.js).

Hopefully this will be fixed soon. In the meantime I suggest you disable this extension. 🙁

**Comment by marcosjampietri** [comment]
Horrible. Had to uninstall the extension.

**Comment by alexanderflink** [comment]
I understand the frustration. This is however as I pointed out a Nova 5 bug – they seem to have introduced a crash whenever using [this](https://docs.nova.app/api-reference/completion-item/#additionaltextedits) property, which is required for this extension to work properly. I suggest you file a bug report to the Nova team about it. :)

**Comment by carlosgavina** [comment]
Thanks for taking a look @alexanderflink. Following the issue on the Nova dev forum, seems they have confirmed the issue. Lets hope for a quick fix and update from them 🤞

**Comment by alexanderflink** [comment]
Hey all! I can confirm this is resolved in the latest version of Nova! Happy code completing!

**Comment by marcosjampietri** [comment]
thanks God!!!

cheers mate
