### ISSUE TITLE
Any Plans for Pro Accounts?

### ISSUE THREAD

**Issue by SuEric** [alexanderflink/nova-tabnine#8]

**Comment by alexanderflink** [comment]
Hi! I would definitely like to look into that. I don't have a pro account and I couldn't find anything in the TabNine client documentation on that. Do you have an example on how it works in other editors? Thanks!

**Comment by frees11** [comment]
He probably means access to this page:

![image](https://user-images.githubusercontent.com/1942987/114537461-83f42900-9c52-11eb-8d91-c9c72395422a.png)

This is from phpstorm, I also have tabnine in vscode and thats seems to be different tabnine instance

![image](https://user-images.githubusercontent.com/1942987/114537602-b00faa00-9c52-11eb-9ee3-af1597db1ef0.png)

**Comment by ghost** [comment]
@alexanderflink This page can already be accessed through your plugin by typing `TabNine::config` and pressing enter in the Nova editor 🙂

**Comment by alexanderflink** [comment]
> @alexanderflink This page can already be accessed through your plugin by typing `TabNine::config` and pressing enter in the Nova editor 🙂

Cool! I had no idea! 😀  I'll make sure to add that to the description. Thanks!

@SuEric @frees11 Is this what you're looking for?

**Comment by frees11** [comment]
Thats ok for me thanks

**Comment by sunilshenoy** [comment]
Can you please let me know where I type TabNine::config? I tried it within the Local Terminal and it did not work for me.

Thank you.

**Comment by JeffreyPYL** [comment]
> > @alexanderflink This page can already be accessed through your plugin by typing `TabNine::config` and pressing enter in the Nova editor 🙂
> 
> Cool! I had no idea! 😀 I'll make sure to add that to the description. Thanks!
> 
> @SuEric @frees11 Is this what you're looking for?

I am not sure where to type in `TabNine::config`. I tried through the Nova command palette but nothing happened.

**Comment by sunilshenoy** [comment]
You can type this in any file you have open. 

I typed it within a PHP file I was working on and typing this triggered tabnine config to open up the browser.
