### ISSUE TITLE
When editing php file tabnine doesn't suggest variables names. 

### ISSUE THREAD

**Issue by frees11** [alexanderflink/nova-tabnine#9]
When editing php file tabnine doesn't suggest variables names. It's not even shown when string starts with $

![image](https://user-images.githubusercontent.com/1942987/114536830-c36e4580-9c51-11eb-8d9e-19ff23d13ae1.png)

It should work like this

![image](https://user-images.githubusercontent.com/1942987/114536879-d41ebb80-9c51-11eb-9c3e-e7e51b506a73.png)

**Comment by alexanderflink** [comment]
I believe this is simply because the autocompletion in Nova does not allow TabNine to override the default completions, not much I can do about it currently.
